### ISSUE TITLE
Clarification on Recipes

### ISSUE THREAD

**Issue by pbauman** [idaholab/civet#178]
After looking at the example recipes, I think I follow what's going on, but I did have a couple of doubts and wanted to clarify my current understanding.

1. Each of the "steps" in the recipe is executed in the order that it is in the .cfg file? The reference one mentions that each name must be unique, but doesn't confirm the order of execution. (I'm inferring from the example moose test and looking at moosebuild.org that they are executed in order, but I wanted to be sure.)

2. I see each step of the recipe basically is just calling a shell script in the `scripts` directory. I see from the instructions where the `civet_recipes` directory should sit, but where should the `scripts` directory sit? As in the in example repo, i.e. at the same level as the `recipes` directory, or should there be a `recipes/scripts` directory?

3. I see on the moosebuild.org page that some of the repos, e.g. moose, show build tracking against devel branchs and master branches, where as the libmesh one does not. How does that work?

4. Is it possible to control when a recipe is executed when it is being simultaneously executed with other recipes? For example, if I have 4 recipes that will be triggered by a PR and I'm fine with the server load that 3 of them will put on, but the 4th one I know is going to be killer (e.g. I execute all the tests on an increasing number of processors), is there a way for me to set "don't execute this recipe until all others in this batch are finished"? Or setting a max load in make kind of my only option?

Thanks much!

**Comment by brianmoose** [comment]
1. I updated the recipe template. Yes, they are executed in the same order that they are defined.
2. All filenames in a recipe are relative to the top level of the `civet_recipes` repository. They are not required to be at the same level as the `recipes` directory but I always liked to keep them separate. 
3. CIVET doesn't show status on branches that it doesn't test. Some repositories don't have any recipes attached to the `master` branch so they don't show up. This also means that if you have recipes attached to the branch `foo` then it would show up on CIVET. Pull requests don't set the status of a branch so if you only have pull request recipes then no branches show up. For example, the `package_builder` repository on moosebuild.org.
4. You can have dependencies in the recipes. The first 3 recipes might not have any dependencies so they would be available to run immediately. The fourth could have in its recipe file
    ```
    [PullRequest Dependencies]
    filename0=recipes/recipe0.cfg
    filename1=recipes/recipe1.cfg
    filename2=recipes/recipe2.cfg
    ```
    Then it would only start up once all the other ones have finished (and passed). You can also order the jobs by setting the priority for each recipe. Higher priority jobs are run first. If you are only going to run a single client along with your server then the recipes will run serially. Setting the long running recipe to a lower priority will run it last.

**Comment by pbauman** [comment]
Thanks much for the very quick and helpful responses and updating the Wiki. I'm working on this again today, will follow up with more questions or notification of success.

**Comment by pbauman** [comment]
OK, I think I understand what's going on in the recipe, more or less. Thanks!
