### ISSUE TITLE
Steps for Enabling Upstream Changes/Fixes

### ISSUE THREAD

**Issue by pbauman** [idaholab/civet#187]
I notice some updates/fixes coming into CIVET. What steps should I take to integrate them on my running server and client? Do I just need to `git pull`? Do I need to additionally restart the server and client? Other additional steps? Thanks for any clarification. (This one isn't burning, so no rush on the response is needed.)

**Comment by brianmoose** [comment]
I updated the wiki https://github.com/idaholab/civet/wiki/Updating-from-upstream
Let me know if you need further clarification.

**Comment by pbauman** [comment]
Perfect, thanks!
