### ISSUE TITLE
Code coverage support?

### ISSUE THREAD

**Issue by roystgnr** [idaholab/civet#194]
Not sure whether this is a feature request or just a documentation request, but is there any way we can get Civet to spit out gcov output after it's run a test suite?  I just saw http://codecov.io/ output for the first time (at https://github.com/libqueso/queso/pull/527), and getting "current coverage is X%; merging will increase/decrease coverage by Y%" on every PR is pretty sweet.

**Comment by pbauman** [comment]
CC me

**Comment by dmcdougall** [comment]
https://github.com/codecov/example-c#travis-ci

> All other CI you can simply run bash <(curl -s https://codecov.io/bash)

cc @pbauman

**Comment by friedmud** [comment]
We already do for MOOSE. See all of the "Code Coverage" links here (toward
the bottom): http://mooseframework.org/documentation/

Should be able to do it for libMesh.

Derek

**Comment by brianmoose** [comment]
Having a diff of code coverage is a cool feature. I think using codecov.io would already be possible with the current Civet. It would just require recipe changes to run the coverage command and then run their bash script which presumably prints out the diff, which then can be posted as a comment to the PR. We would probably have to run the same stuff on the repo default branch so they have a reference point for the diff.

If you wanted a replacement for codecov.io, that would take a bit more work :)

By the way, if you do want code coverage for libmesh we can easily add it to run on merges to the master branch and store it on mooseframework.org (we already store libmesh doxygen there, although it is only the libmesh version that comes with MOOSE master)

**Comment by pbauman** [comment]
Along these lines, have folks figured out how to hook into the "Build Passing" badge to display on the GitHub page? My (very skim) searching only finds Travis-specific stuff.

**Comment by brianmoose** [comment]
We have something on the civet github page. [![Build status](https://www.moosebuild.org/44/branch_status.svg)](https://www.moosebuild.org/repo/19/)
The relevant bit of markdown is

```
[![Build status](https://www.moosebuild.org/44/branch_status.svg)](https://www.moosebuild.org/repo/19/)
```
The URL endpoints aren't the best as the 44 and 19 are internal database ids. If there is interest in this sort of thing I can easily add a `/<repo>/<branch>/branch_status.svg` endpoint as well. This hasn't been used much so if there are any improvements to it that you would like to see, just let me know.

**Comment by pbauman** [comment]
Cool. To be clear, the URL above would be the same for my local server except for the beginning part (`BASE_URL`), i.e. `https://www.moosebuild.org`?

> If there is interest in this sort of thing I can easily add a /<repo>/<branch>/branch_status.svg endpoint as well.

There is, but it's squarely in the "would be nice to have" category, particularly if the existing paths work for any CIVET server (modulo of course the BASE_URL).

**Comment by brianmoose** [comment]
The ids would change depending on the branch and repo, which is why these endpoints aren't very user friendly.
You would have to replace the 44 to your branch id and the 19 to your repository id.
You can find these by navigating to the respective pages and seeing the id in the URL.
A lot of URL endpoints would certainly be improved by using a more human approach, ie instead of `/repo/19/` it would be `/repo/idaholab/civet`.

**Comment by brianmoose** [comment]
I added the friendly branch status endpoint.
The new markdown is
```
[![Build status](https://www.moosebuild.org/idaholab/civet/devel/branch_status.svg)](https://www.moosebuild.org/repo/idaholab/civet/)
```

**Comment by brianmoose** [comment]
Code coverage is best left up to individual civet recipes, not in civet itself.  So I am going to close this.
