### ISSUE TITLE
Dashboard information isn't quite correct for in-progress builds

### ISSUE THREAD

**Issue by permcody** [idaholab/civet#302]
This week the build servers are down so very few jobs are getting done. It looks like the ticket status is based on the last status that was run and not necessarily correct when the aggregate is considered as a whole. 

For instance, many of the prechecks have completed successfully and the ticket status reflects this by showing green for those tickets even though the tests haven't started running. 

I believe that an in-complete build should either show white or yellow if we can make that work. Red is fine if it fails one of the targets.

**Comment by brianmoose** [comment]
Yes, this is related to #281 
The plan is to have event/ticket status be white until it starts a job, then it is yellow until it is complete. Maybe make it purple if all the jobs left to run are waiting for activation
