### ISSUE TITLE
Clean Stale PRs from Status View

### ISSUE THREAD

**Issue by pbauman** [idaholab/civet#331]
There were a few days where my CIVET server was down (because the box was down due to a power outage). During that time, several PRs were merged. However, the server didn't pick up these were merged and they're still in the status list on CIVET as open. Is there a way for me to tell CIVET that these are merged/closed or to tell it to go check the repo in question and update the status? Not a big deal, but it would help clean up the page.

**Comment by brianmoose** [comment]
You can find the failed event on GitHub (Settings->Webhooks->your_webhook) and redeliver it.
You can also just edit the CIVET PR directly on `<hostname>/admin/ci/pullrequest`. Find the PR, click on the "Closed" checkbox and save.

I do like the idea of a "sync" operation though, it can be annoying going through the open PRs on github and matching what PRs CIVET thinks are open.

**Comment by pbauman** [comment]
OK, I used the GitHub solution (there were only 3 to redeliver so it wasn't *too* annoying). A sync operation would be great, so I'll leave this issue open as a feature request, but feel free to close it if it becomes clear such a thing would be untenable. Thanks!
