### ISSUE TITLE
Auto merge GitHub PRs

### ISSUE THREAD

**Issue by brianmoose** [idaholab/civet#369]
One of the nice features of GitLab is the "Merge when pipeline succeeds", which GitHub currently lacks.
Civet could try to do this through the GitHub API. When done testing (and everything passes) it could check if there is an approved review on the PR and if so then merge it through the API.
If that is a bit much, it could check for the existence of a "Auto merge" label or something.

We might want to consider what would happen when a PR is "Allowed to fail". We usually want to take a look at this to make sure it is OK.

**Comment by brianmoose** [comment]
@rwcarlsen @aeslaughter

**Comment by rwcarlsen** [comment]
don't automerge on allowed to fail.  And also don't merge if "do not merge" label is set.
