### ISSUE TITLE
Run previously auto canceled events/jobs on failure

### ISSUE THREAD

**Issue by brianmoose** [idaholab/civet#392]
On a moose push to devel event, if one or more of the jobs fail, then we want to run the corresponding job on a previous push event that was auto canceled. This allows to determine on which event the job actually broke.

We could also uncancel **all** jobs on a previous event with the hope the a previous event will be OK and be able to merge into master.
Given that it is somewhat common to have random failures that work after invalidating, I am not sure we want to do this. 
 
@permcody Thoughts?

**Comment by permcody** [comment]
> We could also uncancel all jobs on a previous event with the hope the a previous event will be OK and be able to merge into master.

I think un-cancelling **all ** is the way to go here. You are right that a spurious failure might start a whole new build unecessarily, but we said last week that if we are here, we could always stop the event by cancelling a target manually. So if we are here and this happens, I think we should be able to cancel an event and force the build system to pick a new "current", perhaps the original one again if it's at the top of the list and the failed target has been invalidated.
