### ISSUE TITLE
https instead of http

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/civet#445]
I'm not sure if this is the correct place to submit this issue, or whether moose or somewhere else would be more appropriate.

Currently if a MOOSE PR fails the clang-format test, the output is something like:

> A patch was auto generated and copied [here](http://mooseframework.inl.gov/docs/PRs/12371/style.patch)  
You can directly apply the patch by running, in the top level of your repository:
> `curl -s http://mooseframework.inl.gov/docs/PRs/12371/style.patch | git apply -v`  

The "http" should be "https"

**Comment by lindsayad** [comment]
Closed by https://github.com/idaholab/civet_recipes/pull/1193
