### ISSUE TITLE
Show most current N events rather than N table rows

### ISSUE THREAD

**Issue by dschwen** [idaholab/civet#462]
Some events occupy multiple rows. Do not count those rows as events.

**Comment by permcody** [comment]
Looks like this has been deployed on the external site but it's not working 😢

**Comment by dschwen** [comment]
Hm, I tested it with local override in my Chrome browser. Let me check. 

On I see the problem! Only the first continuation line has a `_999` suffix. The next one has `_998` and so on. One sec, that's an easy fix.
