### ISSUE TITLE
Remove spaces from filenames/directories of CIVET downloads

### ISSUE THREAD

**Issue by jwpeterson** [idaholab/civet#471]
This is pretty minor, but hopefully it's also pretty simple to fix. When you download the results because they are too long to view in the browser, the filename you get has a space in it e.g. "results_453744_Test debug.tar.gz", as does the directory embedded in the tarball. This makes it slightly more annoying than necessary to deal with and IMO the spaces should be replaced by underscores.

**Comment by aeslaughter** [comment]
This doesn't fix the problem, but I added some python tools to download these results based on git SHA and create files such as "result_1234.tar.gz". Depending on how often you are doing the downloading, this might help.

**Comment by jwpeterson** [comment]
OK, thanks! I will have to update my copy of MOOSE ;-)

**Comment by milljm** [comment]
What the hell is this!? hahah you guys want your jobs back? 😆
