### ISSUE TITLE
Enhanced scheduling capabilities

### ISSUE THREAD

**Issue by permcody** [idaholab/civet#495]
The inner workings of how CIVET manages to publish scheduled tasks is a bit of a mystery. With the Elders gone, what us mere mortals know is that CIVET is capable of creating new "events" based on a periodic schedule for clients to pickup, which is outside of the normal on-demand (trigger) creation of these events. Right now, it is our belief that we can only have a single scheduled trigger (currently daily), which limits what we can do. Every scheduled event is always run and always on the same schedule.

This has served us reasonably well for years as all of our projects have had the same nightly requirement to run heavier tests. With the new scope of being able to periodically produce binaries though, we would like to enhance CIVET to allow us to trigger certain recipes at completely different intervals (e.g. Project A wants weekly builds of a "soft-release", Project B is updated much less frequently so "monthly" is fine). Fleshing out a new capability to have greater control of when specific recipes are triggered based on time would be a huge help in meeting these needs.

Implementation Ideas:
I'm not even sure how the current periodic scheduling even works, but I think it would be really cool if we could add a new field right in the `[Main]` configuration section to specify the scheduling:

```
schedule = 0 2 * * 0          # (Sunday mornings at 2AM)
...
schedule = 0 3 1,15 * *       # The 1st and 15th of every month
```

There might be good python packages that can handle arbitrary scheduling strings available, if there are I'm up for some other syntax. Cron is tried and true so you might start there since it's pretty easy to support very flexible scheduling with just Cron.

**Comment by brianmoose** [comment]
Civet just processes web requests. So scheduling of these events is handled by a cron job on the server (or anywhere really) that just issues the appropriate web request (with the proper authorization) that triggers the creation of the jobs.  Project A and Project B can already do jobs at different times, as specified in the crontab. The only missing part to get more flexibility is that currently **all** manual events for Project A get scheduled at the same time so something like nightly testing and monthly binary generation for Project A is currently not possible. It would be easy to add a `manual_event_group` tag in the recipe though, so something like `manual_event_group = heavy` or `manual_event_group = generate_binaries`.  The group would be specified in the endpoint and the cron job would just hit different web endpoints at different times.

It does suck that all this isn't more transparent and the scheduling isn't specified in the recipe. Currently the monkey doing civet has to manually edit the crontab. It might make sense for Civet to use your proposed cron syntax then have a web endpoint that generates a suitable crontab for all projects. I am not sure if civet itself should be updating the system crontab but an external program (called by cron!) could hit the endpoint and update the system crontab. This would make everything nicely automated and obvious when things are going to run.

Anyway, hopefully this helps the poor sucker that works on this!

**Comment by permcody** [comment]
Thanks @brianmoose for your suggestions. That all makes sense. 

What about the possibility of having a timing thread inside the web server so that we don't rely so heavily on Cron? This thread could essentially call back to the server every minute and then we could choose when/how to act based on that regularly callback. I'm not against cron, just looking at ways to make this a little more self-contained.

**Comment by milljm** [comment]
We still use cron for other tasks. Like recipe updates, canceling old jobs, and of course the nightly runs... (glancing over the current cron). It may make sense to continue using cron, unless we have a 'server thread' also performing this new tasks.

**Comment by brianmoose** [comment]
The only real server in use is probably nginx which is just the web server that calls civet stuff for everything except static files. I don't think nginx has the functionality to do a timing thread but it might be possible to write a custom nginx module to do it. Maybe apache has something? Don't know. 

I looked into various python schedulers when I was at INL for use in other areas of civet (basically to decouple responding to web requests and processing web requests that take a long time). So it is certainly doable. At the time I felt the increase in complexity wasn't worth it but if more things start using a scheduler then that might change.

As @milljm said, we use cron for other things but there could easily be just one "management" command that could run every minute or something that updates recipes, cancels old jobs, figures out what new jobs to schedule, etc. This one command could either be called by cron or a simple stand alone program that just loops forever. So it is pretty doable to become self contained, just need to write some more code!
